### ISSUE TITLE
Compile file

### ISSUE THREAD

**Issue by mp3096** [hookFang/Youtube-Bot-Views#1]
Where is compiled file located cannt find it ? If you can make it available would bee great. Or if it’s already available where is it?

**Comment by hookFang** [comment]
Just open the gradle project on a IDE, make sure you have have JDK installed and run the project on IDE

**Comment by mp3096** [comment]
https://prnt.sc/wnq5fq
Compiled fine but when i open file inside build> libs> youtube view bot 1.0 snapshot.jar file it does not do anything when i used cmd to debug i got this error
C/xxxx/Downloads\Youtube-Bot-Views-master\Youtube-Bot-Views-master\build\libs>java -jar Youtube-View-Bot-1.0-SNAPSHOT.jar
no main manifest attribute, in Youtube-View-Bot-1.0-SNAPSHOT.jar

i check that manifest file is located at \build\tmp\jar
but still getting this error

**Comment by hookFang** [comment]
Hmm I am not completely sure on how to help you here, are you running the project on an IDE ?

**Comment by mp3096** [comment]
Yes neatbean ide
